name: asafni
description: "تطبيق إسعاف فوري يربط المرضى بالمسعفين"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI packages
  cupertino_icons: ^1.0.8
  lottie: ^2.6.0
  cached_network_image: ^3.3.0
  provider: ^6.1.2
  
  # Maps and Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.1
  
  
  # Storage
  shared_preferences: ^2.2.1
  
  # Network and API
  http: ^1.1.0
  url_launcher: ^6.1.14
  
  # Media
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
  #   - assets/icons/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
  #       - asset: assets/fonts/Cairo-Black.ttf
  #         weight: 900
